# Generated by Django 3.1.2 on 2020-11-25 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactadmin',
            name='contact_email',
            field=models.EmailField(max_length=200),
        ),
        migrations.AlterField(
            model_name='contactadmin',
            name='contact_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='contactadmin',
            name='contact_subject',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='contactuser',
            name='contact_email',
            field=models.EmailField(max_length=200),
        ),
        migrations.AlterField(
            model_name='contactuser',
            name='contact_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='contactuser',
            name='contact_subject',
            field=models.CharField(max_length=200),
        ),
    ]
