# Generated by Django 3.1.2 on 2021-08-30 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='')),
                ('url', models.URLField(blank=True, null=True)),
                ('detail', models.CharField(max_length=200)),
            ],
        ),
    ]
