# Generated by Django 3.1.2 on 2021-03-08 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserMembershipSubscription',
        ),
    ]
