# Generated by Django 3.1.2 on 2021-03-12 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0003_usermembershipsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='membership_plan_id',
            field=models.CharField(default=33333, max_length=40),
            preserve_default=False,
        ),
    ]
