# Generated by Django 3.1.2 on 2021-03-12 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0004_membership_membership_plan_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='price',
        ),
    ]
