# Generated by Django 3.1.2 on 2021-03-13 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0005_auto_20210312_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermembershipsubscription',
            name='customer_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
