# Generated by Django 3.1.2 on 2021-03-13 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0006_usermembershipsubscription_customer_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermembershipsubscription',
            name='customer_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
