# Generated by Django 3.1.2 on 2021-03-13 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0007_usermembershipsubscription_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermembershipsubscription',
            name='customer_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usermembershipsubscription',
            name='customer_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usermembershipsubscription',
            name='customer_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
