# Generated by Django 3.1.2 on 2021-08-22 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0008_auto_20210313_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='membership_plan_id',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
