# Generated by Django 3.1.2 on 2021-08-30 22:28

import colorful.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Layout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pics', models.ImageField(default='profile_pics/profile_pics.jpg', upload_to='profile_pics')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('background_image', models.ImageField(default='profile/backgroundImage.jpg', upload_to='background_image')),
                ('background_color', models.CharField(choices=[('dark', 'dark'), ('light', 'light')], default='light', max_length=10)),
                ('primary_color', colorful.fields.RGBColorField(default='#100F0F')),
                ('secondary_color', colorful.fields.RGBColorField(default='#838FF')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motto', models.CharField(blank=True, max_length=100, null=True)),
                ('main_skill', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('phone_number', models.IntegerField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('about', models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
