# Generated by Django 3.1.2 on 2020-11-21 20:48

import colorful.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='')),
                ('url', models.URLField(blank=True, null=True)),
                ('detail', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('percent', models.PositiveIntegerField(default=75)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='')),
                ('description', models.CharField(max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('detail', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pics', models.ImageField(default='profile_pics/profile_pics.jpg', upload_to='profile_pics')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('background_image', models.ImageField(default='profile/backgroundImage.jpg', upload_to='background_image')),
                ('motto', models.CharField(blank=True, max_length=100, null=True)),
                ('main_skill', models.CharField(blank=True, max_length=100, null=True)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('phone_number', models.IntegerField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('about', models.TextField(blank=True, max_length=1000, null=True)),
                ('portfolio_version', models.CharField(choices=[('portfolio_v1', 'portfolio_v1'), ('portfolio_v2', 'portfolio_v2'), ('portfolio_v3', 'portfolio_v3'), ('portfolio_v4', 'portfolio_v4')], default='portfolio_v1', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Layout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', colorful.fields.RGBColorField()),
                ('secondary_color', colorful.fields.RGBColorField()),
                ('background_color', models.CharField(choices=[('dark', 'dark'), ('light', 'light')], default='light', max_length=10)),
                ('carousel_1_name', models.CharField(max_length=50)),
                ('carousel_1_description', models.TextField()),
                ('carousel_1_image', models.ImageField(default='carousel/carousel_1.jpg', upload_to='carousel')),
                ('carousel_2_name', models.CharField(max_length=50)),
                ('carousel_2_description', models.TextField()),
                ('carousel_2_image', models.ImageField(default='carousel/carousel_2.jpg', upload_to='carousel')),
                ('carousel_3_name', models.CharField(max_length=50)),
                ('carousel_3_image', models.ImageField(default='carousel/carousel_3.jpg', upload_to='carousel')),
                ('carousel_3_description', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
