# Generated by Django 3.1.2 on 2020-11-21 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='end_date',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='resume',
            name='start_date',
            field=models.CharField(max_length=10),
        ),
    ]
