# Generated by Django 3.1.2 on 2021-09-24 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='layout',
            name='portfolio_version',
            field=models.OneToOneField(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio_app.portfoliotemplate'),
        ),
        migrations.AddField(
            model_name='layout',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='users.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='layout',
            name='background_image',
            field=models.ImageField(default='layout/backgroundImage.jpg', upload_to='background_image'),
        ),
        migrations.AlterField(
            model_name='layout',
            name='profile_pics',
            field=models.ImageField(default='layout/profile_pics.png', upload_to='profile_pics'),
        ),
    ]
