# Generated by Django 3.1.2 on 2020-11-21 22:00

from django.db import migrations
import fontawesome_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('_profile', '0002_auto_20201121_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='image',
            field=fontawesome_5.fields.IconField(blank=True, max_length=60, null=True),
        ),
    ]
