# Generated by Django 3.1.2 on 2021-09-10 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_profile', '0003_profile_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layout',
            name='profile_pics',
            field=models.ImageField(default='profile/profile_pics.png', upload_to='profile_pics'),
        ),
    ]
