# Generated by Django 3.1.2 on 2020-11-23 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_profile', '0005_auto_20201122_2307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layout',
            name='carousel_1_description',
        ),
        migrations.RemoveField(
            model_name='layout',
            name='carousel_1_image',
        ),
        migrations.RemoveField(
            model_name='layout',
            name='carousel_1_name',
        ),
        migrations.RemoveField(
            model_name='layout',
            name='carousel_2_description',
        ),
        migrations.RemoveField(
            model_name='layout',
            name='carousel_2_image',
        ),
        migrations.RemoveField(
            model_name='layout',
            name='carousel_2_name',
        ),
        migrations.RemoveField(
            model_name='layout',
            name='carousel_3_description',
        ),
        migrations.RemoveField(
            model_name='layout',
            name='carousel_3_image',
        ),
        migrations.RemoveField(
            model_name='layout',
            name='carousel_3_name',
        ),
    ]
