# Generated by Django 3.1.2 on 2021-09-10 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_profile', '0005_auto_20210910_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layout',
            name='background_image',
            field=models.ImageField(default='layout/backgroundImage.jpg', upload_to='background_image'),
        ),
        migrations.AlterField(
            model_name='layout',
            name='profile_pics',
            field=models.ImageField(default='layout/profile_pics.png', upload_to='profile_pics'),
        ),
    ]
