# Generated by Django 3.1.2 on 2020-11-30 20:13

import colorful.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_profile', '0006_auto_20201123_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layout',
            name='primary_color',
            field=colorful.fields.RGBColorField(default='#FFFFFF'),
        ),
        migrations.AlterField(
            model_name='layout',
            name='secondary_color',
            field=colorful.fields.RGBColorField(default='#000000'),
        ),
    ]
