# Generated by Django 3.1.2 on 2021-09-24 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('_profile', '0007_auto_20210922_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layout',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
