# Generated by Django 3.1.2 on 2020-12-20 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_profile', '0008_auto_20201207_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='background_image',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_pics',
        ),
        migrations.AddField(
            model_name='layout',
            name='background_image',
            field=models.ImageField(default='profile/backgroundImage.jpg', upload_to='background_image'),
        ),
        migrations.AddField(
            model_name='layout',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='layout',
            name='profile_pics',
            field=models.ImageField(default='profile_pics/profile_pics.jpg', upload_to='profile_pics'),
        ),
    ]
