# Generated by Django 3.1.2 on 2021-01-01 23:35

import colorful.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_profile', '0009_auto_20201220_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layout',
            name='primary_color',
            field=colorful.fields.RGBColorField(default='#100F0F'),
        ),
        migrations.AlterField(
            model_name='layout',
            name='secondary_color',
            field=colorful.fields.RGBColorField(default='#838FF'),
        ),
    ]
