# Generated by Django 3.1.2 on 2021-03-04 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_profile', '0013_auto_20210228_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='portfolio_version',
        ),
        migrations.AddField(
            model_name='layout',
            name='portfolio_version',
            field=models.CharField(choices=[('portfolio_v1', 'portfolio_v1'), ('portfolio_v2', 'portfolio_v2'), ('portfolio_v3', 'portfolio_v3'), ('portfolio_v4', 'portfolio_v4')], default='portfolio_v1', max_length=20),
        ),
    ]
