# Generated by Django 3.1.2 on 2021-03-06 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0003_portfoliotemplate_portfolio_version'),
        ('_profile', '0014_auto_20210304_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layout',
            name='portfolio_version',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home_page.portfoliotemplate'),
        ),
    ]
