# Generated by Django 3.1.2 on 2021-03-06 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_profile', '0015_auto_20210306_2128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='user',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='user',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='user',
        ),
        migrations.DeleteModel(
            name='Resume',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='Skills',
        ),
        migrations.DeleteModel(
            name='Testimonial',
        ),
    ]
