# Generated by Django 3.1.2 on 2021-03-06 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('_profile', '0016_auto_20210306_2223'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('portfolio_version', models.CharField(max_length=30)),
                ('tag', models.CharField(choices=[('Graphics', 'Graphics'), ('Web development', 'Web development'), ('UI/Ux', 'UI/Ux')], max_length=20)),
                ('image', models.ImageField(upload_to='home_page/portfolio_tag')),
            ],
        ),
        migrations.AlterField(
            model_name='layout',
            name='portfolio_version',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='_profile.portfoliotemplate'),
        ),
    ]
