# Generated by Django 3.1.2 on 2021-03-07 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_profile', '0017_auto_20210306_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliotemplate',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
