# Generated by Django 3.1.2 on 2021-07-31 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0008_portfoliotemplate'),
        ('_profile', '0019_portfoliotemplate_paid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.AlterField(
            model_name='layout',
            name='portfolio_version',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio_app.portfoliotemplate'),
        ),
        migrations.DeleteModel(
            name='PortfolioTemplate',
        ),
    ]
