# Generated by Django 3.1.2 on 2020-11-09 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20201027_2113'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
