# Generated by Django 3.1.2 on 2020-11-28 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectitem',
            name='tag',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
