# Generated by Django 3.1.2 on 2021-03-14 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0005_resume_service_skills_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectitem',
            name='instagram',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectitem',
            name='twitter',
            field=models.BooleanField(default=False),
        ),
    ]
