# Generated by Django 3.1.2 on 2021-07-31 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolio_app', '0007_auto_20210315_2047'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('portfolio_version', models.CharField(max_length=30)),
                ('tag', models.CharField(choices=[('Graphics', 'Graphics'), ('Web development', 'Web development'), ('UI/Ux', 'UI/Ux')], max_length=20)),
                ('image', models.ImageField(upload_to='home_page/portfolio_tag')),
                ('price', models.IntegerField(default=0)),
                ('paid', models.BooleanField(default=True)),
            ],
        ),
    ]
