# Generated by Django 3.1.2 on 2021-02-11 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('tag', models.CharField(choices=[('Graphics', 'Graphics'), ('Web development', 'Web development'), ('UI/Ux', 'UI/Ux')], max_length=20)),
                ('image', models.ImageField(upload_to='home_page/portfolio_tag')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('info', models.CharField(max_length=70)),
                ('image', models.ImageField(upload_to='home_page/service')),
            ],
        ),
        migrations.CreateModel(
            name='TestimonialModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='testimonial')),
                ('description', models.CharField(max_length=50)),
            ],
        ),
    ]
