# Generated by Django 3.1.2 on 2021-02-28 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageTestimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='testimonial')),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameModel(
            old_name='Service',
            new_name='HomePageService',
        ),
        migrations.DeleteModel(
            name='TestimonialModel',
        ),
    ]
