# Generated by Django 3.1.2 on 2021-03-06 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0002_auto_20210228_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliotemplate',
            name='portfolio_version',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
