# Generated by Django 3.1.2 on 2021-03-06 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_profile', '0017_auto_20210306_2235'),
        ('home_page', '0003_portfoliotemplate_portfolio_version'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PortfolioTemplate',
        ),
    ]
