# Generated by Django 3.1.2 on 2021-08-30 22:28

from django.db import migrations, models
import fontawesome_5.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('percent', models.PositiveIntegerField(default=75)),
                ('icon', fontawesome_5.fields.IconField(blank=True, max_length=60, null=True)),
            ],
        ),
    ]
